# Generated by Django 5.2.4 on 2026-05-28 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Biomarker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('METABOLIC', 'Metabolic Health'), ('CARDIOVASCULAR', 'Cardiovascular Health'), ('INFLAMMATION', 'Inflammation'), ('HORMONAL', 'Hormonal Health'), ('LIVER', 'Liver Health'), ('KIDNEY', 'Kidney Health'), ('THYROID', 'Thyroid Health'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('range_min', models.FloatField(help_text='Normal range lower bound')),
                ('range_max', models.FloatField(help_text='Normal range upper bound')),
                ('optimal_min', models.FloatField(blank=True, help_text='Optimal range lower bound', null=True)),
                ('optimal_max', models.FloatField(blank=True, help_text='Optimal range upper bound', null=True)),
                ('unit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TestKit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('biomarker_count', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('active', models.BooleanField(default=True, help_text='Whether this test kit is currently active and available for ordering')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(choices=[('PROVIDER', 'healthcare'), ('INDIVIDUAL', 'individual')], default='INDIVIDUAL', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('ethnicity', models.CharField(blank=True, max_length=100)),
                ('sport', models.CharField(blank=True, max_length=100)),
                ('health_conditions', models.TextField(blank=True, max_length=100)),
                ('dietary_preferences', models.TextField(blank=True, max_length=100)),
                ('allergies', models.TextField(blank=True, max_length=100)),
                ('dietary_recall', models.TextField(blank=True)),
                ('exercise_recall', models.TextField(blank=True)),
                ('dietary_typicality', models.PositiveSmallIntegerField(blank=True, help_text='How typical the 24-hour recall is on a 5-level scale from unusual to always', null=True)),
                ('dietary_preference_mode', models.CharField(blank=True, help_text='Whether the client wants similar or different recommendations', max_length=20)),
                ('preferred_cuisines', models.TextField(blank=True)),
                ('avoided_cuisines', models.TextField(blank=True)),
                ('weekly_exercise_routine', models.TextField(blank=True)),
                ('exercise_days_per_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('exercise_types', models.TextField(blank=True)),
                ('provider_notes', models.TextField(blank=True)),
                ('fitness_goal', models.CharField(blank=True, max_length=100)),
                ('nutritional_goal', models.TextField(blank=True)),
                ('referral_code', models.CharField(blank=True, help_text='Unique code used for provider referral links. Auto-generated for PROVIDER accounts.', max_length=16, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referred_by', models.ForeignKey(blank=True, help_text='The provider who referred this patient.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_patients', to='core.client')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BiomarkerTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.JSONField(blank=True, help_text='Legacy raw data', null=True)),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biomarker_tests', to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='DietLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recall', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_logs', to='core.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recall', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_logs', to='core.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('meals', models.TextField(help_text='JSON or comma-separated list of meals')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('membership_type', models.SmallIntegerField(default=1)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of kits ordered')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Order Confirmed'), ('SHIPPED', 'Shipped'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('forward_tracking_number', models.CharField(blank=True, max_length=100)),
                ('return_tracking_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.client')),
                ('test_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.testkit')),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('ORDER_PLACED', 'Order Placed'), ('SHIPPED', 'Shipped'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_events', to='core.order')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cardholder_name', models.CharField(max_length=200)),
                ('card_last_four', models.CharField(help_text='Last 4 digits of card number', max_length=4)),
                ('card_brand', models.CharField(blank=True, help_text='e.g. Visa, Mastercard', max_length=50)),
                ('expiry_month', models.PositiveSmallIntegerField()),
                ('expiry_year', models.PositiveSmallIntegerField()),
                ('payment_method', models.CharField(default='card', max_length=100)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='Stripe PaymentIntent ID', max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('street_address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_address', to='core.paymentinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_shipped', models.DateTimeField()),
                ('tracking_number', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_info', to='core.order')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='core.client')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase', to='core.order')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='core.paymentinfo')),
                ('test_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='core.testkit')),
            ],
        ),
        migrations.CreateModel(
            name='KitBarcodeAssignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_number', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('barcode_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kit_barcode_assignments', to='core.client')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barcode_assignment', to='core.order')),
                ('test_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcode_assignments', to='core.testkit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BiomarkerResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('status', models.CharField(blank=True, choices=[('OPTIMAL', 'Optimal'), ('NORMAL', 'Normal'), ('LOW', 'Low'), ('HIGH', 'High')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('biomarker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.biomarker')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.biomarkertest')),
            ],
            options={
                'unique_together': {('test', 'biomarker')},
            },
        ),
    ]
