# Generated by Django 5.2.4 on 2025-10-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="type",
            field=models.CharField(
                choices=[("TRAINER", "TRAINER"), ("CLIENT", "CLIENT")], max_length=10
            ),
        ),
        migrations.AlterModelTable(
            name="client",
            table=None,
        ),
    ]
