# Generated by Django 5.2.4 on 2026-05-28 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_membership_paymentinfo_shippinginfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitbarcodeassignment',
            name='order_number',
        ),
        migrations.AlterField(
            model_name='kitbarcodeassignment',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barcode_assignment', to='core.order'),
        ),
    ]
