# Generated by Django 5.2.4 on 2026-03-26 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_membership_paymentinfo_shippinginfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestKit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('biomarker_count', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='biomarker',
            name='category',
            field=models.CharField(choices=[('METABOLIC', 'Metabolic Health'), ('CARDIOVASCULAR', 'Cardiovascular Health'), ('INFLAMMATION', 'Inflammation'), ('HORMONAL', 'Hormonal Health'), ('LIVER', 'Liver Health'), ('KIDNEY', 'Kidney Health'), ('THYROID', 'Thyroid Health'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='biomarker',
            name='optimal_max',
            field=models.FloatField(blank=True, help_text='Optimal range upper bound', null=True),
        ),
        migrations.AddField(
            model_name='biomarker',
            name='optimal_min',
            field=models.FloatField(blank=True, help_text='Optimal range lower bound', null=True),
        ),
        migrations.AddField(
            model_name='paymentinfo',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentinfo',
            name='card_brand',
            field=models.CharField(blank=True, help_text='e.g. Visa, Mastercard', max_length=50),
        ),
        migrations.AddField(
            model_name='paymentinfo',
            name='card_last_four',
            field=models.CharField(default=0, help_text='Last 4 digits of card number', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentinfo',
            name='cardholder_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentinfo',
            name='expiry_month',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentinfo',
            name='expiry_year',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='biomarker',
            name='range_max',
            field=models.FloatField(help_text='Normal range upper bound'),
        ),
        migrations.AlterField(
            model_name='biomarker',
            name='range_min',
            field=models.FloatField(help_text='Normal range lower bound'),
        ),
        migrations.AlterField(
            model_name='biomarkertest',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biomarker_tests', to='core.client'),
        ),
        migrations.AlterField(
            model_name='biomarkertest',
            name='data',
            field=models.JSONField(blank=True, help_text='Legacy raw data', null=True),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.client'),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='payment_method',
            field=models.CharField(default='card', max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('street_address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_address', to='core.paymentinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Order Confirmed'), ('SHIPPED', 'Shipped'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=20)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.client')),
                ('test_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.testkit')),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('ORDER_PLACED', 'Order Placed'), ('SHIPPED', 'Shipped'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_events', to='core.order')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='core.client')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase', to='core.order')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='core.paymentinfo')),
                ('test_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='core.testkit')),
            ],
        ),
        migrations.CreateModel(
            name='BiomarkerResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('status', models.CharField(blank=True, choices=[('OPTIMAL', 'Optimal'), ('NORMAL', 'Normal'), ('LOW', 'Low'), ('HIGH', 'High')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('biomarker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.biomarker')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.biomarkertest')),
            ],
            options={
                'unique_together': {('test', 'biomarker')},
            },
        ),
    ]
