# Generated by Django 5.2.4 on 2025-10-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_client_type_alter_client_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="type",
            field=models.CharField(
                choices=[("TRAINER", "TRAINER"), ("CLIENT", "CLIENT")],
                default="CLIENT",
                max_length=10,
            ),
        ),
    ]
