# Generated by Django 5.2.4 on 2026-03-28 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_testkit_biomarker_category_biomarker_optimal_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='referral_code',
            field=models.CharField(blank=True, help_text='Unique code used for provider referral links. Auto-generated for PROVIDER accounts.', max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='referred_by',
            field=models.ForeignKey(blank=True, help_text='The provider who referred this patient.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_patients', to='core.client'),
        ),
    ]
