# Generated by Django 5.2.4 on 2025-10-12 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_profile_date_of_birth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="client",
        ),
        migrations.AddField(
            model_name="client",
            name="profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.profile",
            ),
        ),
    ]
