# Generated by Django 5.2.4 on 2026-06-01 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_kitbarcodeassignment_collected_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='dietary_recall',
        ),
        migrations.RemoveField(
            model_name='client',
            name='exercise_recall',
        ),
    ]
