# Generated by Django 5.2.4 on 2025-10-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_profile_client_client_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dietary_preferences',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='health_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(default='male', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
