# Generated by Django 5.2.4 on 2026-07-02 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_client_dietary_recall_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='approved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'PROVIDER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_recommendations', to='core.client'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='biomarker_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.biomarkertest'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='dietary_draft',
            field=models.JSONField(blank=True, help_text='AI generated initial diet plan', null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='dietary_final',
            field=models.JSONField(blank=True, help_text='Refined final diet plan', null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='doctor_feedback',
            field=models.TextField(blank=True, help_text='Doctor feedback to AI for adjustments'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='doctor_notes',
            field=models.TextField(blank=True, help_text='Additional public notes from doctor directly to patient'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='exercise_draft',
            field=models.JSONField(blank=True, help_text='AI generated initial exercise plan', null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='exercise_final',
            field=models.JSONField(blank=True, help_text='Refined final exercise plan', null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'AI Draft Generated'), ('PENDING_REVIEW', 'Pending Doctor Review'), ('REVISING', 'AI Revising'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='text',
            field=models.CharField(blank=True, help_text='Fallback or summary recommendation text', max_length=500),
        ),
    ]
