# Generated by Django 5.2.4 on 2026-06-20 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_client_dietary_recall_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kit_barcode', models.CharField(db_index=True, max_length=100, unique=True)),
                ('result_info', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('SHIPPING', 'Shipping'), ('DELIVERED', 'Delivered'), ('COLLECTED', 'Collected'), ('PENDING', 'Pending'), ('TESTING', 'Testing'), ('FINISHED', 'Finished'), ('CONFIRMED', 'Order Confirmed'), ('SHIPPED', 'Shipped'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='KitCollection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kit_barcode', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('SHIPPING', 'Shipping'), ('DELIVERED', 'Delivered'), ('COLLECTED', 'Collected'), ('PENDING', 'Pending'), ('TESTING', 'Testing'), ('FINISHED', 'Finished')], default='CREATED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diet_log', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kit_collection', to='core.dietlog')),
                ('exercise_log', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kit_collection', to='core.exerciselog')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kit_collection', to='core.order')),
                ('shipping_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kit_collections', to='core.shippinginfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kit_collections', to='core.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
