# Generated by Django 5.2.4 on 2026-07-05 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_kitresult_alter_order_status_kitcollection'),
        ('core', '0006_recommendation_approved_at_and_more'),
    ]

    operations = [
    ]
