# Generated by Django 5.2.4 on 2026-04-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_order_status_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, help_text='Stripe PaymentIntent ID', max_length=255, null=True),
        ),
    ]
