# Generated by Django 5.2.4 on 2026-04-30 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_paymentinfo_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of kits ordered'),
        ),
        migrations.AddField(
            model_name='testkit',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Commission percentage for providers/dietitians (e.g., 10 for 10%)', max_digits=5),
        ),
        migrations.CreateModel(
            name='DietitianCommission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kit_quantity', models.PositiveIntegerField(default=1, help_text='Number of kits in the order')),
                ('kit_price', models.DecimalField(decimal_places=2, help_text='Price per kit at time of order', max_digits=10)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=10, help_text='Commission percentage (e.g., 10 for 10%)', max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, help_text='Calculated commission amount (kit_price * kit_quantity * commission_percent / 100)', max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('stripe_transfer_id', models.CharField(blank=True, help_text='Stripe transfer ID when payment is sent', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='When the commission was paid out', null=True)),
                ('order', models.OneToOneField(help_text='Order that triggered the commission', on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='core.order')),
                ('provider', models.ForeignKey(help_text='Provider/Dietitian who earned the commission', on_delete=django.db.models.deletion.CASCADE, related_name='earned_commissions', to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('min_quantity', models.PositiveIntegerField(help_text='Minimum quantity for this tier')),
                ('max_quantity', models.PositiveIntegerField(blank=True, help_text='Maximum quantity for this tier, null for unlimited', null=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage (e.g., 5.00 for 5%)', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_tiers', to='core.testkit')),
            ],
            options={
                'ordering': ['min_quantity'],
                'unique_together': {('test_kit', 'min_quantity')},
            },
        ),
    ]
