# Generated by Django 5.2.4 on 2026-07-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20260705_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitcollection',
            name='collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
