# Generated by Django 5.2.4 on 2026-04-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order_quantity_testkit_commission_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='avoided_cuisines',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='dietary_preference_mode',
            field=models.CharField(blank=True, help_text='Whether the client wants similar or different recommendations', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='dietary_recall',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='dietary_typicality',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How typical the 24-hour recall is on a 1-10 scale', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='exercise_days_per_week',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='exercise_types',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='preferred_cuisines',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='provider_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='weekly_exercise_routine',
            field=models.TextField(blank=True),
        ),
    ]
