# Generated by Django 5.2.4 on 2026-07-06 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_kitcollection_collected_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitbarcodeassignment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='test_kit',
        ),
        migrations.AddField(
            model_name='order',
            name='barcode_assignment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='core.kitbarcodeassignment'),
        ),
    ]
