# Generated by Django 5.2.4 on 2025-10-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='type',
            field=models.CharField(choices=[('PROVIDER', 'PROVIDER'), ('INDIVIDUAL', 'INDIVIDUAL')], default='INDIVIDUAL', max_length=10),
        ),
    ]
