# Generated by Django 5.2.4 on 2026-07-09 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_kitbarcodeassignment_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='barcode_assignment',
        ),
        migrations.AddField(
            model_name='kitbarcodeassignment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcode_assignments', to='core.order'),
        ),
    ]
