# Generated by Django 5.2.4 on 2026-05-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_client_avoided_cuisines_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietitiancommission',
            name='kit_price',
            field=models.FloatField(help_text='Price per kit at time of order'),
        ),
    ]
