# Generated by Django 5.2.4 on 2026-07-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_order_barcode_assignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('SHIPPING', 'Shipping'), ('DELIVERED', 'Delivered'), ('COLLECTED', 'Collected'), ('TESTING', 'Testing'), ('FINISHED', 'Finished'), ('CONFIRMED', 'Order Confirmed'), ('SHIPPED', 'Shipped'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=20),
        ),
    ]
