# Generated by Django 5.2.4 on 2026-05-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_dietitiancommission_kit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testkit',
            name='commission_percent',
        ),
        migrations.AddField(
            model_name='testkit',
            name='active',
            field=models.BooleanField(default=True, help_text='Whether this test kit is currently active and available for ordering'),
        ),
        migrations.DeleteModel(
            name='DietitianCommission',
        ),
    ]
