# Generated by Django 5.2.4 on 2025-10-25 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_client_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biomarker',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='biomarker',
            name='recorded_at',
        ),
        migrations.RemoveField(
            model_name='biomarker',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='BiomarkerTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.JSONField()),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
        ),
    ]
