# Generated by Django 5.2.4 on 2026-05-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_testkit_commission_percent_testkit_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='exercise_recall',
            field=models.TextField(blank=True),
        ),
    ]
