# Generated by Django 5.2.4 on 2025-10-25 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_biomarker_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biomarker',
            name='range_max',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biomarker',
            name='range_min',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
