# Generated by Django 5.2.4 on 2025-10-25 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_biomarker_range_max_biomarker_range_min'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biomarker',
            name='value',
        ),
    ]
