# Generated by Django 5.2.4 on 2026-05-13 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_client_exercise_recall'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recall', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_logs', to='core.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recall', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_logs', to='core.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
