# Generated by Django 5.2.4 on 2026-07-12 03:19

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='allergies',
            field=core.fields.EncryptedTextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='avoided_cuisines',
            field=core.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='bio',
            field=core.fields.EncryptedTextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_of_birth',
            field=core.fields.EncryptedDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='dietary_preference_mode',
            field=core.fields.EncryptedCharField(blank=True, help_text='Whether the client wants similar or different recommendations', max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='dietary_preferences',
            field=core.fields.EncryptedTextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='dietary_typicality',
            field=core.fields.EncryptedIntegerField(blank=True, help_text='How typical the 24-hour recall is on a 5-level scale from unusual to always', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='ethnicity',
            field=core.fields.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='exercise_days_per_week',
            field=core.fields.EncryptedIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='exercise_types',
            field=core.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=core.fields.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='fitness_goal',
            field=core.fields.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=core.fields.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='health_conditions',
            field=core.fields.EncryptedTextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='height',
            field=core.fields.EncryptedFloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=core.fields.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='location',
            field=core.fields.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='nutritional_goal',
            field=core.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='preferred_cuisines',
            field=core.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='provider_notes',
            field=core.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='sport',
            field=core.fields.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='weekly_exercise_routine',
            field=core.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='weight',
            field=core.fields.EncryptedFloatField(blank=True, null=True),
        ),
    ]
