# Generated by Django 5.2.4 on 2025-10-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_biomarker_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='biomarker',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='biomarker',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
