# Generated by Django 5.2.4 on 2026-05-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_dietlog_exerciselog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dietary_typicality',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How typical the 24-hour recall is on a 5-level scale from unusual to always', null=True),
        ),
    ]
