# Generated by Django 5.2.4 on 2025-12-14 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_biomarker_description_alter_biomarker_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="type",
            field=models.CharField(
                choices=[("PROVIDER", "healthcare"), ("INDIVIDUAL", "individual")],
                default="INDIVIDUAL",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
