# Generated by Django 5.2.4 on 2026-07-12

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_client_allergies_alter_client_avoided_cuisines_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_of_birth',
            field=core.fields.EncryptedDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='dietary_typicality',
            field=core.fields.EncryptedIntegerField(blank=True, help_text='How typical the 24-hour recall is on a 5-level scale from unusual to always', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='exercise_days_per_week',
            field=core.fields.EncryptedIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='height',
            field=core.fields.EncryptedFloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='weight',
            field=core.fields.EncryptedFloatField(blank=True, null=True),
        ),
    ]