# Generated by Django 5.2.4 on 2026-05-19 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_client_dietary_typicality"),
    ]

    operations = [
        migrations.CreateModel(
            name="KitBarcodeAssignment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("barcode_number", models.CharField(db_index=True, max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kit_barcode_assignments",
                        to="core.client",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="barcode_assignment",
                        to="core.order",
                    ),
                ),
                (
                    "test_kit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="barcode_assignments",
                        to="core.testkit",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]