# Generated by Django 5.2.4 on 2026-05-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_kitbarcodeassignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kitbarcodeassignment",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name="kit_barcode_assignments",
                to="core.client",
            ),
        ),
    ]
