# Generated by Django 5.2.4 on 2026-07-12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_encrypt_typed_client_fields'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                "ALTER TABLE core_client ALTER COLUMN date_of_birth TYPE text USING date_of_birth::text",
                "ALTER TABLE core_client ALTER COLUMN dietary_typicality TYPE text USING dietary_typicality::text",
                "ALTER TABLE core_client ALTER COLUMN exercise_days_per_week TYPE text USING exercise_days_per_week::text",
                "ALTER TABLE core_client ALTER COLUMN height TYPE text USING height::text",
                "ALTER TABLE core_client ALTER COLUMN weight TYPE text USING weight::text",
            ],
            reverse_sql=[
                "ALTER TABLE core_client ALTER COLUMN date_of_birth TYPE date USING NULLIF(date_of_birth, '')::date",
                "ALTER TABLE core_client ALTER COLUMN dietary_typicality TYPE integer USING NULLIF(dietary_typicality, '')::integer",
                "ALTER TABLE core_client ALTER COLUMN exercise_days_per_week TYPE integer USING NULLIF(exercise_days_per_week, '')::integer",
                "ALTER TABLE core_client ALTER COLUMN height TYPE double precision USING NULLIF(height, '')::double precision",
                "ALTER TABLE core_client ALTER COLUMN weight TYPE double precision USING NULLIF(weight, '')::double precision",
            ],
        ),
    ]