# Generated by Django 5.2.4 on 2025-12-14 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_client_type_alter_client_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="profile",
        ),
        migrations.AddField(
            model_name="client",
            name="allergies",
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="client",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="dietary_preferences",
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="client",
            name="ethnicity",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="client",
            name="fitness_goal",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="client",
            name="gender",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="client",
            name="health_conditions",
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="client",
            name="height",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="nutritional_goal",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="client",
            name="sport",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="client",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="client",
            name="last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="client",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
