# Generated by Django 5.2.4 on 2026-05-21 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_kitbarcodeassignment_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippinginfo",
            name="order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipping_info",
                to="core.order",
            ),
        ),
    ]
