# Generated by Django 5.2.4 on 2026-07-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_client_security_answer_client_security_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='use_custom_key',
            field=models.BooleanField(default=False),
        ),
    ]
