# Generated by Django 5.2.4 on 2026-08-04 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_client_use_custom_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KitResult',
        ),
        migrations.AddField(
            model_name='biomarkertest',
            name='barcode_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biomarker_tests', to='core.kitbarcodeassignment'),
        ),
        migrations.AlterField(
            model_name='biomarker',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
