# Generated by Django 5.2.4 on 2026-08-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_delete_kitresult_biomarkertest_barcode_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biomarker',
            name='average_value',
            field=models.FloatField(blank=True, help_text='Average value calculated from test data', null=True),
        ),
    ]
