# Generated by Django 5.2.4 on 2026-08-07 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_biomarker_average_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biomarkertest',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biomarker_tests', to='core.client'),
        ),
        migrations.CreateModel(
            name='BiomarkerReport',
            fields=[
                ('primary_id', models.AutoField(primary_key=True, serialize=False)),
                ('report', models.TextField(help_text='Textual report content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test_ids', models.JSONField(blank=True, default=list, help_text='List of BiomarkerTest IDs in chronological order')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biomarker_reports', to='core.client')),
            ],
        ),
    ]
