# Generated by Django 5.2.4 on 2026-08-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_biomarkertest_client_biomarkerreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='biomarker',
            name='additional_information',
            field=models.JSONField(blank=True, help_text='Additional metadata and statistics as JSON', null=True),
        ),
    ]
