# Generated by Django 5.2.4 on 2026-08-07 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_biomarker_additional_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biomarker',
            name='description',
        ),
    ]
