# Generated by Django 5.2.4 on 2026-09-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_biomarker_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitcollection',
            name='step_progress',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed progress state for each collection step'),
        ),
    ]
