# Generated by Django 5.2.4 on 2026-09-29 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_order_status_to_delivery_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExercisePlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('summary', models.TextField(blank=True, help_text='Exercise programming overview')),
                ('frequency', models.CharField(blank=True, help_text='e.g. 3-4 sessions per week', max_length=100)),
                ('activities', models.JSONField(blank=True, default=list, help_text='List of individual exercise activities')),
                ('precautions', models.JSONField(blank=True, default=list, help_text='List of safety precautions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('biomarker_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercise_plans', to='core.biomarkertest')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_plans', to='core.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
