## regsiter account
POST http://localhost:8000/api/register http/1.1
Content-Type: application/json

{
    "username": "johndoe",
    "password": "password123",
    "first_name": "John",
    "last_name": "Doe",
    "email": "john.doe@email.com",
    "type": "CLIENT",
    "profile":{
        "ethnicity":"Black",
        "allergies":"None",
        "sport":"balls",
        "fitness_goal":"my goal 1",
        "nutritional_goal":"goal 2"
    }
}

### create client
POST http://localhost:8000/api/client http/1.1
Content-Type: application/json

{
    "first_name": "John",
    "last_name": "Doe",
    "email": "john.doe@email.com",
    "type": "CLIENT",
    "profile":{
        "ethnicity":"Black",
        "allergies":"None",
        "sport":"balls",
        "fitness_goal":"my goal 1",
        "nutritional_goal":"goal 2"
    }
}
### user info
GET http://localhost:8000/api/client/1 http/1.1

### meal plan
GET http://localhost:8000/api/mealPlan?client_id=2 http/1.1